# Generated by Django 3.0.8 on 2020-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='requirement',
            name='finish',
            field=models.IntegerField(choices=[(0, '执行中'), (1, '已归档'), (3, '未开始')], default=3),
        ),
    ]
