# Generated by Django 3.0.8 on 2020-07-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200718_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='owner',
            new_name='user',
        ),
    ]
